void flot_rec_var (float * );
void DispFloat(float);
void DispFlot(float);
void SendChar(char );
void DispString (unsigned char *, unsigned char );
void DispDeci(unsigned char);
char CheckACK(void);
void usart_rec_n_sign(unsigned char* , unsigned char );
void usart_rec_n(unsigned char* , unsigned char );
void SendYack(void);
void SendNack(void);
void  uart_rec(unsigned char*);
void DispFloatWo(float);
void DispRunPara(char);
